In [41]:
import pandas as pd
import re

df = pd.read_csv('apc.csv',encoding = "ISO-8859-1")

df.rename(columns={'COST (£) charged to Wellcome (inc VAT when charged)':'Cost (£)'}, inplace=True)
df.columns =[column.replace(" ", "_") for column in df.columns]
df['Cost_(£)'] = df['Cost_(£)'].str.replace('£', '')
df['Cost_(£)'] = df['Cost_(£)'].str.replace('$', '')
df['Cost_(£)'] = df['Cost_(£)'].str.strip()
df['Cost_(£)'] = df['Cost_(£)'].astype(float)
df['Journal_title'] = df['Journal_title'].str.strip()
df['Journal_title'] = df['Journal_title'].str.replace('JOURNAL OF BIOLOGICAL CHEMISTRY', 'Journal of Biological Chemistry')
df['Journal_title'] = df['Journal_title'].str.replace('The journal of Biological Chemistry', 'Journal of Biological Chemistry')
df['Journal_title'] = df['Journal_title'].str.replace('The Journal of Biological Chemistry', 'Journal of Biological Chemistry')
df['Journal_title'] = df['Journal_title'].str.replace('Neuroimage: Clinical', 'Neuroimage')
df['Journal_title'] = df['Journal_title'].str.replace('PNAS', 'Proceedings of the National Academy of Sciences')
#df['Journal_title'] = df['Journal_title'].str.replace('PNAS (Proceedings of the National Academy of Sciences of the United States of America', 'Proceedings of the National Academy of Sciences')
df['Journal_title'] = df['Journal_title'].str.replace('Proceddings of the National Academy of Sciences of USA', 'Proceedings of the National Academy of Sciences')
df['Journal_title'] = df['Journal_title'].str.replace('PNAS USA', 'Proceedings of the National Academy of Sciences')
df['Journal_title'] = df['Journal_title'].str.replace('PLoS 1', 'PLoS ONE')
df['Journal_title'] = df['Journal_title'].str.replace('PLOS  ONE', 'PLoS ONE')
df['Journal_title'] = df['Journal_title'].str.replace('PloS One', 'PLoS ONE')
df['Journal_title'] = df['Journal_title'].str.replace('PLOS One', 'PLoS ONE')
df['Journal_title'] = df['Journal_title'].str.replace('Plos One', 'PLoS ONE')
df['Journal_title'] = df['Journal_title'].str.replace('PLoS One', 'PLoS ONE')


df.head()

,PMID/PMCID,Publisher,Journal_title,Article_title,Cost_(£)
0,NaN,CUP,Psychological Medicine,Reduced parahippocampal cortical thickness in ...,0.00
1,PMC3679557,ACS,Biomacromolecules,Structural characterization of a Model Gram-ne...,2381.04
2,23043264 PMC3506128,ACS,J Med Chem,"Fumaroylamino-4,5-epoxymorphinans and related ...",642.56
3,23438330 PMC3646402,ACS,J Med Chem,Orvinols with mixed kappa/mu opioid receptor a...,669.64
4,23438216 PMC3601604,ACS,J Org Chem,Regioselective opening of myo-inositol orthoes...,685.88

In [42]:
counts = df.groupby('Journal_title').count()
counts.sort_values(by=['Article_title'], ascending=False).head()

,PMID/PMCID,Publisher,Article_title,Cost_(£)
Journal_title,,,,
PLoS ONE,169,178,178,178
Journal of Biological Chemistry,57,58,58,58
Proceedings of the National Academy of Sciences,28,28,28,28
Nucleic Acids Research,23,24,24,24
Human Molecular Genetics,16,18,18,18

In [58]:
pl = df['Cost_(£)'].loc[df['Journal_title'] == 'PLoS ONE']
print('1) \"PLoS ONE\" with 178 Article title')
print('Mean of the open-access cost per article for \"PLoS ONE\" is: {}'.format(round(pl.mean(), 2)))
print('Median of the open-access cost per article for \"PLoS ONE\" is: {}'.format(round(pl.median(), 2)))
print('Standard deviation of the open-access cost per article for \"PLoS ONE\" is: {}'.format(round(pl.std(), 2)))
print('\n')
jbc = df['Cost_(£)'].loc[df['Journal_title'] == 'Journal of Biological Chemistry']
print('2) \"Journal of Biological Chemistry\" with 58 Article title')
print('Mean of the open-access cost per article for \"Journal of Biological Chemistry\" is: {}'.format(round(jbc.mean(), 2)))
print('Median of the open-access cost per article for \"Journal of Biological Chemistry\" is: {}'.format(round(jbc.median(), 2)))
print('Standard deviation of the open-access cost per article for \"Journal of Biological Chemistry\" is: {}'.format(round(jbc.std(), 2)))
print('\n')
pnas = df['Cost_(£)'].loc[df['Journal_title'] == 'Proceedings of the National Academy of Sciences']
print('3) \"Proceedings of the National Academy of Sciences\" with 28 Article title')
print('Mean of the open-access cost per article for \"PNAS\" is: {}'.format(round(pnas.mean(), 2)))
print('Median of the open-access cost per article for \"PNAS\" is: {}'.format(round(pnas.median(), 2)))
print('Standard deviation of the open-access cost per article for \"PNAS\" is: {}'.format(round(pnas.std(), 2)))
print('\n')
nar = df['Cost_(£)'].loc[df['Journal_title'] == 'Nucleic Acids Research']
print('4) \"Nucleic Acids Research\" with 24 Article title')
print('Mean of the open-access cost per article for \"Nucleic Acids Research\" is: {}'.format(round(nar.mean(), 2)))
print('Median of the open-access cost per article for \"Nucleic Acids Research\" is: {}'.format(round(nar.median(), 2)))
print('Standard deviation of the open-access cost per article for \"Nucleic Acids Research\" is: {}'.format(round(nar.std(), 2)))
print('\n')
hmg = df['Cost_(£)'].loc[df['Journal_title'] == 'Human Molecular Genetics']
print('5) \"Human Molecular Genetics\" with 178 Article title')
print('Mean of the open-access cost per article for \"Human Molecular Genetics\" is: {}'.format(round(hmg.mean(), 2)))
print('Median of the open-access cost per article for \"Human Molecular Genetics\" is: {}'.format(round(hmg.median(), 2)))
print('Standard deviation of the open-access cost per article for \"Human Molecular Genetics\" is: {}'.format(round(hmg.std(), 2)))

1) "PLoS ONE" with 178 Article title
Mean of the open-access cost per article for "PLoS ONE" is: 30073.35
Median of the open-access cost per article for "PLoS ONE" is: 900.42
Standard deviation of the open-access cost per article for "PLoS ONE" is: 165980.64


2) "Journal of Biological Chemistry" with 58 Article title
Mean of the open-access cost per article for "Journal of Biological Chemistry" is: 18640.73
Median of the open-access cost per article for "Journal of Biological Chemistry" is: 1319.55
Standard deviation of the open-access cost per article for "Journal of Biological Chemistry" is: 131119.9


3) "Proceedings of the National Academy of Sciences" with 28 Article title
Mean of the open-access cost per article for "PNAS" is: 36468.12
Median of the open-access cost per article for "PNAS" is: 728.83
Standard deviation of the open-access cost per article for "PNAS" is: 188834.76


4) "Nucleic Acids Research" with 24 Article title
Mean of the open-access cost per article for "Nucleic Acids Research" is: 1102.75
Median of the open-access cost per article for "Nucleic Acids Research" is: 852.0
Standard deviation of the open-access cost per article for "Nucleic Acids Research" is: 429.23


5) "Human Molecular Genetics" with 178 Article title
Mean of the open-access cost per article for "Human Molecular Genetics" is: 57483.21
Median of the open-access cost per article for "Human Molecular Genetics" is: 2040.0
Standard deviation of the open-access cost per article for "Human Molecular Genetics" is: 235220.95